(!default-title "Hato Mail Suite")
(!toc-page 0)
(!toc-entry 0 "1" 1 "node_sec_1" "Installation")
(!toc-entry 0 "2" 2 "node_sec_2" "Usage")
(!toc-entry 1 "2.1" 2 "node_sec_2.1" "hato-mta")
(!toc-entry 1 "2.2" 2 "node_sec_2.2" "hato-classify")
(!toc-entry 0 "3" 3 "node_sec_3" "Configuration")
(!toc-entry 0 "4" 4 "node_sec_4" "System Filters")
(!toc-entry 0 "5" 5 "node_sec_5" "User Filters")
(!toc-entry 1 "5.1" 5 "node_sec_5.1" "Filter Language")
(!toc-entry 1 "5.2" 5 "node_sec_5.2" "A Sample Filter")
(!toc-entry 0 "6" 6 "node_sec_6" "Hato-fetch")
(!toc-entry 1 "6.1" 6 "node_sec_6.1" "Hato-fetch Usage")
(!toc-entry 1 "6.2" 6 "node_sec_6.2" "Input Sources")
(!toc-entry 1 "6.3" 6 "node_sec_6.3" "Output Sources")
(!toc-entry 1 "6.4" 6 "node_sec_6.4" "Hato-fetch Comand-line Examples")
(!toc-entry 1 "6.5" 6 "node_sec_6.5" "Hato-fetch Config")
(!toc-entry 1 "6.6" 6 "node_sec_6.6" "Sample hato-fetch Config")
(!toc-entry 0 "7" 7 "node_sec_7" "Library Documentation")
(!last-page-number 7)
(!last-modification-time 1202481564)
(!head-line "")
(!foot-line "\\folio")
